<a href="https://colab.research.google.com/github/Rjmarquart/rjmarquart.github.io/blob/main/CSC114%2C_Mod_2_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab Assignment: Introduction to NumPy, Aggregations, and Universal Functions

# CSC-114

In these lab assignments, I will provide a file for you, as you can see here, and will have code cells present where I want you to insert your code. You can add / remove code cells as you see fit. Just be sure to answer the question(s) posed.

**Note: be sure to turn in notebook with code cells executed or it will be an automatic 0.**

## Task 1: Import Numpy and alias as np.

In [17]:
import numpy as np

## Task 2: Create & print a NumPy array of integers from 1 to 20.

In [18]:
import numpy as np

arr = np.arange(1, 21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## Task 3: Perform & print basic arithmetic operations (+, -, *, /) on said array.

In [19]:
arr = np.arange(1, 21)

print(arr + 5)
print(arr - 2)
print(arr * 3)
print(arr / 2)


[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]
[ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5 10. ]


## Task 4: Calculate & print sum, mean, minimum, standard deviation, and maximum of said array.

In [20]:
print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Maximum:", np.max(arr))


Sum: 210
Mean: 10.5
Minimum: 1
Standard Deviation: 5.766281297335398
Maximum: 20


## Task 5: Use ufuncs to calculate the square root, square, and exponent of each element in said array.

In [21]:
print("\nSquare root:")
print(np.sqrt(arr))
print("\nSquare:")
print(np.square(arr))
print("\nExponent:")
print(np.exp(arr))


Square root:
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595]

Square:
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]

Exponent:
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08 4.85165195e+08]


## Task 6: Create a new NumPy array of random integers between 1 and 100 with a shape of 10x10. Calculate & print the sum of each column in this array.

In [22]:
arr = np.random.randint(1, 101, size=(10, 10))

print("Random array 10x10: ")
print(arr)

column_sums = np.sum(arr, axis=0)

print("\nSum of each column: ")
print(column_sums)

Random array 10x10: 
[[ 65  18  41  77  61  65  71  34  62  24]
 [ 11 100  74  36  72  67  62  33  99  74]
 [ 81  74  67  12  42  60  71  69  17  11]
 [ 86  76  97  12  67   8  62  46  77  24]
 [ 83  35  74  85  21  19  67 100  95  26]
 [100  24  98  79  89   2  25  33  44   5]
 [ 77  83  80  38   7  71  29   5  71  55]
 [ 37  92  16  83  60  80  90  13  53  76]
 [  8  60  31  70  69  41   7  38  17  38]
 [ 19  93  48  90  99  82  41  74  38  69]]

Sum of each column: 
[567 655 626 582 587 495 525 445 573 402]


## Task 7: find & print the transpose of the array.

In [23]:
transpose_arr = arr.T

print("\nTranposed array:")
print(transpose_arr)



Tranposed array:
[[ 65  11  81  86  83 100  77  37   8  19]
 [ 18 100  74  76  35  24  83  92  60  93]
 [ 41  74  67  97  74  98  80  16  31  48]
 [ 77  36  12  12  85  79  38  83  70  90]
 [ 61  72  42  67  21  89   7  60  69  99]
 [ 65  67  60   8  19   2  71  80  41  82]
 [ 71  62  71  62  67  25  29  90   7  41]
 [ 34  33  69  46 100  33   5  13  38  74]
 [ 62  99  17  77  95  44  71  53  17  38]
 [ 24  74  11  24  26   5  55  76  38  69]]


## Task 8: Using the linalg module in NumPy, calculate and print the determinant of this matrix.

In [24]:
print("Matrix:")
print(arr)

determinant = np.linalg.det(arr)

print("\nDeterminant:")
print(determinant)

Matrix:
[[ 65  18  41  77  61  65  71  34  62  24]
 [ 11 100  74  36  72  67  62  33  99  74]
 [ 81  74  67  12  42  60  71  69  17  11]
 [ 86  76  97  12  67   8  62  46  77  24]
 [ 83  35  74  85  21  19  67 100  95  26]
 [100  24  98  79  89   2  25  33  44   5]
 [ 77  83  80  38   7  71  29   5  71  55]
 [ 37  92  16  83  60  80  90  13  53  76]
 [  8  60  31  70  69  41   7  38  17  38]
 [ 19  93  48  90  99  82  41  74  38  69]]

Determinant:
1.1000804988163112e+18
